// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Icons: typeof import('./.vitepress/vitepress/components/globals/icons.vue')['default']
    IRiCodeLine: typeof import('~icons/ri/code-line')['default']
    IRiExternalLinkLine: typeof import('~icons/ri/external-link-line')['default']
    IRiFileCopyLine: typeof import('~icons/ri/file-copy-line')['default']
    Layout: typeof import('./.vitepress/vitepress/components/layout.vue')['default']
    MainColor: typeof import('./.vitepress/vitepress/components/globals/main-color.vue')['default']
    NeutralColor: typeof import('./.vitepress/vitepress/components/globals/neutral-color.vue')['default']
    'NeutralColor.vue': typeof import('./.vitepress/vitepress/components/globals/neutral-color.vue.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SecondaryColors: typeof import('./.vitepress/vitepress/components/globals/secondary-colors.vue')['default']
    Theme: typeof import('./.vitepress/vitepress/components/theme.vue')['default']
    Theme1: typeof import('./.vitepress/vitepress/components/theme1.vue')['default']
    Translation: typeof import('./.vitepress/vitepress/components/translation.vue')['default']
    VersionTag: typeof import('./.vitepress/vitepress/components/dev/VersionTag.vue')['default']
    VpApp: typeof import('./.vitepress/vitepress/components/vp-app.vue')['default']
    VpContent: typeof import('./.vitepress/vitepress/components/vp-content.vue')['default']
    VpDemo: typeof import('./.vitepress/vitepress/components/vp-demo.vue')['default']
    VpExample: typeof import('./.vitepress/vitepress/components/demo/vp-example.vue')['default']
    VpNav: typeof import('./.vitepress/vitepress/components/vp-nav.vue')['default']
    VpNavbar: typeof import('./.vitepress/vitepress/components/vp-navbar.vue')['default']
    VpNotFound: typeof import('./.vitepress/vitepress/components/vp-not-found.vue')['default']
    VpOverlay: typeof import('./.vitepress/vitepress/components/vp-overlay.vue')['default']
    VpSidebar: typeof import('./.vitepress/vitepress/components/vp-sidebar.vue')['default']
    VpSidebarLink: typeof import('./.vitepress/vitepress/components/sidebar/vp-sidebar-link.vue')['default']
    VpSourceCode: typeof import('./.vitepress/vitepress/components/demo/vp-source-code.vue')['default']
  }
}
