export const PKG_PREFIX = '@yu'
export const PKG_NAME = 'yu'
export const PKG_CAMELCASE_NAME = 'YuElement'
export const PKG_CAMELCASE_LOCAL_NAME = 'YuElementLocale'
export const PKG_BRAND_NAME = 'Yu Element'
